version = 1

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 100



#KANGER_KI_BHEN_MERI_GFðŸ˜Ž
